### ISSUE TITLE
Fix contrast on speakers page

### ISSUE THREAD

**Issue by kaitlinnewson** [code4lib/2019.code4lib.org#121]
On the speakers page at https://2019.code4lib.org/speakers/, there are colour contrast issues with many of the fonts.

![screen shot 2018-11-27 at 9 30 10 am](https://user-images.githubusercontent.com/6903515/49088384-2c8ec300-f227-11e8-8218-0e321b4378c1.png)

See http://wave.webaim.org/report#/https://2019.code4lib.org/speakers/# (the contrast tab) for more details.

**Comment by metageeky** [comment]
This is interesting. The contrast ratio for the yellow-orange and the blueish background comes out to be 2.99...:1. 3:1 is the threshold for large text. I'd consider the speaker names to be large enough to be considered large text (plus they are in bold). We're close enough to say this is a false positive accessibility concern, or we could adjust say the orange ever so slightly to things like: #F98F1B. 

The additional issue is wherever the orange text is used on the blue in small cases. There's one such example on the homepage right now (the Doubletree link). I cannot rationalize that as being accessible.

**Comment by phette23** [comment]
I see three red flags on the home page

- in the `a` welcome section, the `p a:-webkit-any-link` rule on line 990 is overriding the `section:nth-of-type(3n+2)` rule on line 218 which would make the link a brighter orange
- both of the small "vote" buttons have insufficient contrast between their orange background & white text, changing the `$btn-primary` color on line 239 of _variables.scss to be `$accent-dark` instead of `$brand-primary` fixes this

I agree the 2.99:1 ratio is probably good enough for the speakers page.
