### ISSUE TITLE
add missing sponsors

### ISSUE THREAD

**Issue by phette23** [code4lib/2019.code4lib.org#126]

**Comment by streeetlamp** [comment]
Added current sponsors from the spreadsheet, I did not add any with TBA or missing logo

**Comment by phette23** [comment]
We were missing OCLC & Blacklight, two of the Gold sponsors. Did they just not have logos in the sponsors image folder?

**Comment by streeetlamp** [comment]
I believe it would have been marked on the spreadsheet as not having a logo yet, my mistake

**Comment by phette23** [comment]
No not your mistake, I'm just trying to figure out what happened. I think the sponsor logos were pretty hard to keep on top of this year. We need a better system. Any input on what would have made it easier for you is appreciated.

**Comment by streeetlamp** [comment]
I just overlooked the spreadsheet and made an assumption that all logo images in the folder were good to post and I think the spreadsheet was slightly out of sync. Also I think the images that were in place (and supposed to be there) I removed due to thinking they were left over from last year or examples, etc. Mostly me overlooking some, I would also divide the task up next year as the number of sponsors is fairly long and its easy to make minor mistakes entering everything
