### ISSUE TITLE
Expand usage of variables in _data/conf.yml

### ISSUE THREAD

**Issue by kaitlinnewson** [code4lib/2019.code4lib.org#64]
There are still some areas where we could probably be using variables in our data. Some that I've noticed are:

- [x] the conference venue
- [x] the conference city/state
- [x] the date range 
- [ ] the contact name/email for keynotes, workshops, and talks 

Feel free to add others to this ticket!

**Comment by kaitlinnewson** [comment]
We could also have variables for dates for re-occurring events, such as game night, the reception, and the newcomer dinner

**Comment by streeetlamp** [comment]
Sponsor Prospectus page could use some of this too for sure

**Comment by snarkshow** [comment]
Is there any way I could assist with this issue?

**Comment by snarkshow** [comment]
My effort at scanning the old C4L websites for possible variables.  I'm finding I'm having some trouble identifying exactly what can/cannot be a variable vs what needs to be hardcoded because it's too specific:

https://docs.google.com/document/d/1LwBqw4zbgZKoVYE5f6ABBYJcF-FZvRsRG_1GIgGvk7o/edit?usp=sharing
