### ISSUE TITLE
Add volunteering section to website

### ISSUE THREAD

**Issue by kaitlinnewson** [code4lib/2019.code4lib.org#83]
As we frequently have open volunteer opportunities for the conference, it would be great to have a section for this on the homepage, similar to the sections for proposals and voting. The button could either link to a contact for the volunteering opportunity, or to the relevant wiki section.

Current open volunteer opportunities include duty officers and others on the wiki - https://wiki.code4lib.org/Code4Lib_2019_Conference_Committees

Each committee could have a conf section, with a true/false variable if they're looking for volunteers.

**Comment by kaitlinnewson** [comment]
@phette23 is there any cut off date for signing up to join a committee, e.g. the on-site committee?

This is what I have so far: 
![screen shot 2018-10-31 at 10 10 29 am](https://user-images.githubusercontent.com/6903515/47793686-3b03c080-dcf5-11e8-92d2-e75efce68dce.png)

**Comment by phette23** [comment]
That's a good question and I think it varies—some committees might have hard start dates because they need to have an initial meeting and perform some task (e.g. send out a CFP) while others are more or less rolling. In general having end dates makes sense and we'll just have to speculate what it is for the onsite committees, perhaps something like a month before the conference.

**Comment by kaitlinnewson** [comment]
For now I just have a general conference committees entry, but we could break it up into separate committees if there was a need.
